### PR TITLE
Creates a world and launches the robot in it

### PR DESCRIPTION
**Pull request by francocipollone**
This PR:

 - Creates a world describing a house.
 - Adds furniture to that house. The furniture are downloaded-models.
 - Spawns the robot in the new world. 
 - Adds a mesh to the robot (just for fun)

Screenshot from 2020-05-01 16-57-41

### CODE REVIEW

**Comment by BarceloChristian** [comment]
Oh! And have fun looking at the back of the monitor:
image

**Comment by francocipollone** [comment]
> Cool! I like that you managed to get the world included, the export tag is not really well documented.
> Do you think you could get the visual and collision match?
> collisions

I think that I am going to remove that mesh that I added because it is not accurate. I mean I should use a mesh for the wheels and another mesh for the chassis and the match the visual and the collision right? I just added it because it was fun but I will go back and remove the mesh so to keep it simple.

**Comment by BarceloChristian** [comment]
> > Cool! I like that you managed to get the world included, the export tag is not really well documented.
> > Do you think you could get the visual and collision match?
> > collisions
> 
> I think that I am going to remove that mesh that I added because it is not accurate. I mean I should use a mesh for the wheels and another mesh for the chassis and the match the visual and the collision right? I just added it because it was fun but I will go back and remove the mesh so to keep it simple.

If you can remove the wheels from the meshes, you could use the car mesh both for visuals and collisions, that's the good point.

**Comment by francocipollone** [comment]
I removed the model's mesh. I will attack the inertial matrix in the next PR.

**Pull request merged**
